### PR TITLE
Increase Y plot max to 130 secs

### PR DESCRIPTION
**Pull request by jeanconn**
Increase Y plot max to 130 secs.  Looks like some events with durations greater than 100 are currently omitted from the plot.  I assume the max is 30 * 4.1 secs so 130 secs should get all cases with some padding.

(I misunderstood both what the code is doing and what the max should be -Jean)

### CODE REVIEW

**Comment by taldcroft** [comment]
BTW what is 30 * 4.1?

**Comment by taldcroft** [comment]
I thought the CEBR timeout is something like 3 minutes.

**Comment by jeanconn** [comment]
I thought that for Kalman watch we just cared about the kalman glitch limit
which is 30 and I thought that was applied to the 4.1 second cycle, but I
may be completely confused.

**Comment by jeanconn** [comment]
If we're still doing the CEBR check we shouldn't be in Kalman, right?

**Comment by taldcroft** [comment]
OK, thought some more and CEBR timeout is not relevant here.

I think that the last plot on http://cxc.cfa.harvard.edu/mta/ASPECT/aca_star_acq_time/ is what we want.  This gives the distribution from the start of the acq (or reacq) process to the start of Kalman.   For a reacq you need to add the 30 seconds of no kalman stars prior to starting the reacq, so in theory it could 180 seconds.  This is exceedingly rare, and indeed the peak of the distribution is 60 seconds (+ 30 second for the Kalman glitch) = 90 seconds, which is what we see.

BUT, the actual Kalman outtage time could be larger than 130 seconds.  So I rescind my earlier OK and say just make the limit be `plt.ylim(0, max(130, np.max(y_plot_points))`.  (Assuming there is a `margins` call applied as well).

**Comment by taldcroft** [comment]
It just occurred to me that this long tail in the guide phase is most likely the CEBR check blocking guide search commanding.  We have learned something new since 2006!

**Comment by jeanconn** [comment]
> BUT, the actual Kalman outtage time could be larger than 130 seconds.

I'll think about this some more, I thought we were plotting the interval of low stars within Kalman, not a "Kalman outage time". If we go over 30 samples with too few stars we transition out of Kalman.

**Comment by jeanconn** [comment]
OK, so I thought the point of kalman_watch was to show us the times during Kalman where we had 1 or fewer AOKALSTR so that we could see when we had reacquisitions or when we came *close* to reacquistions, but it looks like these logical intervals of AOKALSTR <= 1 aren't filtered to just be in Kalman intervals.  Right?  So that was my confusion.  I don't see how displaying longer "times" due to reacquisition really helps the plot.  I'd be more interested in just filtering for Kalman.

**Comment by jeanconn** [comment]
Also, current code appears to be filtering all events > 120.

**Comment by taldcroft** [comment]
The point of Kalman watch is to show intervals when the OBC Kalman filter is nominally running but does not have sufficient star inputs to update attitude and bias estimates.

Good point about the 120 arcsec filtering.  I think that can be bumped to 180.  I don't remember how long the "very long" spurious intervals were that I found in development.

**Comment by taldcroft** [comment]
Superceded by #5.

**Pull request closed without merging**
