### PR TITLE
Improve monitor window IR fraction plot and refactor key data structure

### PR DESCRIPTION
**Pull request by taldcroft**
# Description

This improves the monitor window ionizing radiation fraction plot:
- Add a legend showing each perigee time
- Use a consistent color for NPNT and NMAN for each perigee
- Vary both color and plot marker so that up to 50 perigees have a unique color/marker combination.

In addition the `KalmanDropsData` class was changed so that it contains data for a single perigee. Previously it included all the data from all perigees, which was confusing and inconvenient.

This also includes #15.

## Functional testing
```
(ska3) ➜  kalman_watch git:(improve-plot) ✗ python -m kalman_watch.monitor_win_perigee --n-cache 300    
2024-07-23 06:42:21,912 get_manvrs_perigee: Getting maneuvers from 2024:160:10:42:21.911 to 2024:204:10:42:21.912
2024-07-23 06:42:23,679 get_manvrs_perigee: Getting intervals of Earth blocks from 2024:160:10:42:21.911 to 2024:204:10:42:21.912
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:165:05:03:16.731 to 2024:165:05:22:08.331
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:167:20:31:32.820 to 2024:167:20:49:44.446
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:170:10:03:00.985 to 2024:170:10:13:26.235
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:170:11:47:27.835 to 2024:170:12:17:32.860
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:172:17:34:19.073 to 2024:172:17:38:11.748
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:173:03:39:25.600 to 2024:173:03:53:54.800
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:178:10:46:37.380 to 2024:178:10:56:49.305
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:178:12:05:55.430 to 2024:178:12:15:44.805
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:183:17:11:40.485 to 2024:183:17:41:33.210
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:191:15:40:59.354 to 2024:191:16:11:17.704
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:194:07:09:23.644 to 2024:194:07:39:46.094
2024-07-23 06:42:25,897 get_manvrs_perigee:  Excluding Earth block from 2024:196:22:37:13.084 to 2024:196:23:07:42.709
2024-07-23 06:42:25,920 get_mon_dataset: Getting MON data from 2024:162:11:38:09.640 to 2024:162:12:08:13.640
2024-07-23 06:42:25,920 get_aca_images_cached: Getting ACA images from 2024:162:11:38:09.640 to 2024:162:12:08:13.640
2024-07-23 06:42:26,019 get_ir_thresholds: Getting IR thresholds from 2023:100 to 2023:200
2024-07-23 06:42:26,817 get_mon_dataset: Getting MON data from 2024:162:13:30:36.191 to 2024:162:14:18:55.916
2024-07-23 06:42:26,817 get_aca_images_cached: Getting ACA images from 2024:162:13:30:36.191 to 2024:162:14:18:55.916
2024-07-23 06:42:26,929 get_mon_dataset: Getting MON data from 2024:165:03:57:28.430 to 2024:165:04:30:55.380
2024-07-23 06:42:26,930 get_aca_images_cached: Getting ACA images from 2024:165:03:57:28.430 to 2024:165:04:30:55.380
2024-07-23 06:42:27,081 get_mon_dataset: Getting MON data from 2024:165:04:59:37.381 to 2024:165:05:03:16.731
2024-07-23 06:42:27,081 get_aca_images_cached: Getting ACA images from 2024:165:04:59:37.381 to 2024:165:05:03:16.731
2024-07-23 06:42:27,162 get_mon_dataset: Getting MON data from 2024:165:05:22:08.331 to 2024:165:05:49:56.006
2024-07-23 06:42:27,162 get_aca_images_cached: Getting ACA images from 2024:165:05:22:08.331 to 2024:165:05:49:56.006
2024-07-23 06:42:27,262 get_mon_dataset: Getting MON data from 2024:165:06:09:40.906 to 2024:165:06:43:19.131
2024-07-23 06:42:27,262 get_aca_images_cached: Getting ACA images from 2024:165:06:09:40.906 to 2024:165:06:43:19.131
2024-07-23 06:42:27,363 get_mon_dataset: Getting MON data from 2024:167:20:28:25.245 to 2024:167:20:31:32.820
2024-07-23 06:42:27,363 get_aca_images_cached: Getting ACA images from 2024:167:20:28:25.245 to 2024:167:20:31:32.820
2024-07-23 06:42:27,444 get_mon_dataset: Getting MON data from 2024:167:20:49:44.446 to 2024:167:21:16:06.021
2024-07-23 06:42:27,444 get_aca_images_cached: Getting ACA images from 2024:167:20:49:44.446 to 2024:167:21:16:06.021
2024-07-23 06:42:27,541 get_mon_dataset: Getting MON data from 2024:167:21:51:42.121 to 2024:167:22:25:56.221
2024-07-23 06:42:27,541 get_aca_images_cached: Getting ACA images from 2024:167:21:51:42.121 to 2024:167:22:25:56.221
2024-07-23 06:42:27,641 get_mon_dataset: Getting MON data from 2024:170:10:13:26.235 to 2024:170:10:35:10.035
2024-07-23 06:42:27,642 get_aca_images_cached: Getting ACA images from 2024:170:10:13:26.235 to 2024:170:10:35:10.035
2024-07-23 06:42:27,735 get_mon_dataset: Getting MON data from 2024:170:10:54:55.960 to 2024:170:11:21:14.460
2024-07-23 06:42:27,735 get_aca_images_cached: Getting ACA images from 2024:170:10:54:55.960 to 2024:170:11:21:14.460
2024-07-23 06:42:27,832 get_mon_dataset: Getting MON data from 2024:170:11:47:00.160 to 2024:170:11:47:27.835
2024-07-23 06:42:27,832 get_aca_images_cached: Getting ACA images from 2024:170:11:47:00.160 to 2024:170:11:47:27.835
2024-07-23 06:42:27,844 get_mon_dataset: Not enough images for slot 0 found 4)
2024-07-23 06:42:27,845 get_mon_dataset: Not enough images for slot 1 found 4)
2024-07-23 06:42:27,846 get_mon_dataset: Not enough images for slot 2 found 4)
2024-07-23 06:42:27,846 get_mon_dataset: Not enough images for slot 3 found 4)
2024-07-23 06:42:27,847 get_mon_dataset: Not enough images for slot 4 found 4)
2024-07-23 06:42:27,848 get_mon_dataset: Not enough images for slot 5 found 4)
2024-07-23 06:42:27,849 get_mon_dataset: Not enough images for slot 6 found 4)
2024-07-23 06:42:27,850 get_mon_dataset: Not enough images for slot 7 found 4)
2024-07-23 06:42:27,850 main: No image data between 2024:170:11:47:00.160 and 2024:170:11:47:27.835
2024-07-23 06:42:27,851 get_mon_dataset: Getting MON data from 2024:170:12:17:32.860 to 2024:170:12:43:55.461
2024-07-23 06:42:27,851 get_aca_images_cached: Getting ACA images from 2024:170:12:17:32.860 to 2024:170:12:43:55.461
2024-07-23 06:42:27,950 get_mon_dataset: Getting MON data from 2024:173:01:47:04.175 to 2024:173:02:37:18.700
2024-07-23 06:42:27,950 get_aca_images_cached: Getting ACA images from 2024:173:01:47:04.175 to 2024:173:02:37:18.700
2024-07-23 06:42:28,064 get_mon_dataset: Getting MON data from 2024:173:03:24:00.025 to 2024:173:03:39:25.600
2024-07-23 06:42:28,064 get_aca_images_cached: Getting ACA images from 2024:173:03:24:00.025 to 2024:173:03:39:25.600
2024-07-23 06:42:28,154 get_mon_dataset: Getting MON data from 2024:173:03:53:54.800 to 2024:173:04:12:55.625
2024-07-23 06:42:28,154 get_aca_images_cached: Getting ACA images from 2024:173:03:53:54.800 to 2024:173:04:12:55.625
2024-07-23 06:42:28,247 get_mon_dataset: Getting MON data from 2024:173:04:39:21.300 to 2024:173:05:10:55.501
2024-07-23 06:42:28,247 get_aca_images_cached: Getting ACA images from 2024:173:04:39:21.300 to 2024:173:05:10:55.501
2024-07-23 06:42:28,345 get_mon_dataset: Getting MON data from 2024:175:17:18:14.515 to 2024:175:17:55:55.665
2024-07-23 06:42:28,345 get_aca_images_cached: Getting ACA images from 2024:175:17:18:14.515 to 2024:175:17:55:55.665
2024-07-23 06:42:28,450 get_mon_dataset: Getting MON data from 2024:175:18:49:59.790 to 2024:175:19:41:55.790
2024-07-23 06:42:28,450 get_aca_images_cached: Getting ACA images from 2024:175:18:49:59.790 to 2024:175:19:41:55.790
2024-07-23 06:42:28,567 get_mon_dataset: Getting MON data from 2024:175:20:12:15.165 to 2024:175:20:52:55.691
2024-07-23 06:42:28,567 get_aca_images_cached: Getting ACA images from 2024:175:20:12:15.165 to 2024:175:20:52:55.691
2024-07-23 06:42:28,672 get_mon_dataset: Getting MON data from 2024:178:08:56:25.105 to 2024:178:09:25:56.305
2024-07-23 06:42:28,672 get_aca_images_cached: Getting ACA images from 2024:178:08:56:25.105 to 2024:178:09:25:56.305
2024-07-23 06:42:28,772 get_mon_dataset: Getting MON data from 2024:178:10:18:00.505 to 2024:178:10:46:37.380
2024-07-23 06:42:28,772 get_aca_images_cached: Getting ACA images from 2024:178:10:18:00.505 to 2024:178:10:46:37.380
2024-07-23 06:42:28,910 get_mon_dataset: Getting MON data from 2024:178:10:56:49.305 to 2024:178:11:07:55.555
2024-07-23 06:42:28,911 get_aca_images_cached: Getting ACA images from 2024:178:10:56:49.305 to 2024:178:11:07:55.555
2024-07-23 06:42:29,000 get_mon_dataset: Getting MON data from 2024:178:11:47:12.030 to 2024:178:12:05:55.430
2024-07-23 06:42:29,000 get_aca_images_cached: Getting ACA images from 2024:178:11:47:12.030 to 2024:178:12:05:55.430
2024-07-23 06:42:29,092 get_mon_dataset: Getting MON data from 2024:181:01:44:59.720 to 2024:181:02:35:56.270
2024-07-23 06:42:29,092 get_aca_images_cached: Getting ACA images from 2024:181:01:44:59.720 to 2024:181:02:35:56.270
2024-07-23 06:42:29,206 get_mon_dataset: Getting MON data from 2024:181:03:08:10.445 to 2024:181:03:15:20.945
2024-07-23 06:42:29,206 get_aca_images_cached: Getting ACA images from 2024:181:03:08:10.445 to 2024:181:03:15:20.945
2024-07-23 06:42:29,220 get_mon_dataset: Not enough images for slot 0 found 0)
2024-07-23 06:42:29,221 get_mon_dataset: Not enough images for slot 1 found 0)
2024-07-23 06:42:29,222 get_mon_dataset: Not enough images for slot 2 found 0)
2024-07-23 06:42:29,223 get_mon_dataset: Not enough images for slot 3 found 0)
2024-07-23 06:42:29,224 get_mon_dataset: Not enough images for slot 4 found 0)
2024-07-23 06:42:29,225 get_mon_dataset: Not enough images for slot 5 found 0)
2024-07-23 06:42:29,226 get_mon_dataset: Not enough images for slot 6 found 0)
2024-07-23 06:42:29,227 get_mon_dataset: Not enough images for slot 7 found 0)
2024-07-23 06:42:29,227 main: No image data between 2024:181:03:08:10.445 and 2024:181:03:15:20.945
2024-07-23 06:42:29,227 get_mon_dataset: Getting MON data from 2024:183:16:27:59.559 to 2024:183:16:50:56.135
2024-07-23 06:42:29,227 get_aca_images_cached: Getting ACA images from 2024:183:16:27:59.559 to 2024:183:16:50:56.135
2024-07-23 06:42:29,330 get_mon_dataset: Getting MON data from 2024:183:17:10:41.035 to 2024:183:17:11:40.485
2024-07-23 06:42:29,330 get_aca_images_cached: Getting ACA images from 2024:183:17:10:41.035 to 2024:183:17:11:40.485
2024-07-23 06:42:29,417 get_mon_dataset: Getting MON data from 2024:183:17:41:33.210 to 2024:183:18:02:26.785
2024-07-23 06:42:29,417 get_aca_images_cached: Getting ACA images from 2024:183:17:41:33.210 to 2024:183:18:02:26.785
2024-07-23 06:42:29,520 get_mon_dataset: Getting MON data from 2024:186:07:52:20.924 to 2024:186:08:20:55.749
2024-07-23 06:42:29,520 get_aca_images_cached: Getting ACA images from 2024:186:07:52:20.924 to 2024:186:08:20:55.749
2024-07-23 06:42:29,624 get_mon_dataset: Getting MON data from 2024:186:08:40:40.650 to 2024:186:09:32:26.400
2024-07-23 06:42:29,624 get_aca_images_cached: Getting ACA images from 2024:186:08:40:40.650 to 2024:186:09:32:26.400
2024-07-23 06:42:29,742 get_mon_dataset: Getting MON data from 2024:188:23:22:20.539 to 2024:188:23:50:55.364
2024-07-23 06:42:29,742 get_aca_images_cached: Getting ACA images from 2024:188:23:22:20.539 to 2024:188:23:50:55.364
2024-07-23 06:42:29,845 get_mon_dataset: Getting MON data from 2024:189:00:10:41.289 to 2024:189:01:02:27.040
2024-07-23 06:42:29,845 get_aca_images_cached: Getting ACA images from 2024:189:00:10:41.289 to 2024:189:01:02:27.040
2024-07-23 06:42:29,963 get_mon_dataset: Getting MON data from 2024:191:14:37:31.479 to 2024:191:15:00:55.729
2024-07-23 06:42:29,963 get_aca_images_cached: Getting ACA images from 2024:191:14:37:31.479 to 2024:191:15:00:55.729
2024-07-23 06:42:30,061 get_mon_dataset: Getting MON data from 2024:191:15:39:59.904 to 2024:191:15:40:59.354
2024-07-23 06:42:30,061 get_aca_images_cached: Getting ACA images from 2024:191:15:39:59.904 to 2024:191:15:40:59.354
2024-07-23 06:42:30,144 get_mon_dataset: Getting MON data from 2024:191:16:11:17.704 to 2024:191:16:30:55.429
2024-07-23 06:42:30,145 get_aca_images_cached: Getting ACA images from 2024:191:16:11:17.704 to 2024:191:16:30:55.429
2024-07-23 06:42:30,241 get_mon_dataset: Getting MON data from 2024:194:05:30:57.594 to 2024:194:05:55:56.144
2024-07-23 06:42:30,241 get_aca_images_cached: Getting ACA images from 2024:194:05:30:57.594 to 2024:194:05:55:56.144
2024-07-23 06:42:30,341 get_mon_dataset: Getting MON data from 2024:194:07:09:00.069 to 2024:194:07:09:23.644
2024-07-23 06:42:30,341 get_aca_images_cached: Getting ACA images from 2024:194:07:09:00.069 to 2024:194:07:09:23.644
2024-07-23 06:42:30,352 get_mon_dataset: Not enough images for slot 0 found 3)
2024-07-23 06:42:30,353 get_mon_dataset: Not enough images for slot 1 found 3)
2024-07-23 06:42:30,354 get_mon_dataset: Not enough images for slot 2 found 3)
2024-07-23 06:42:30,354 get_mon_dataset: Not enough images for slot 3 found 3)
2024-07-23 06:42:30,355 get_mon_dataset: Not enough images for slot 4 found 3)
2024-07-23 06:42:30,356 get_mon_dataset: Not enough images for slot 5 found 3)
2024-07-23 06:42:30,357 get_mon_dataset: Not enough images for slot 6 found 3)
2024-07-23 06:42:30,358 get_mon_dataset: Not enough images for slot 7 found 3)
2024-07-23 06:42:30,358 main: No image data between 2024:194:07:09:00.069 and 2024:194:07:09:23.644
2024-07-23 06:42:30,358 get_mon_dataset: Getting MON data from 2024:194:07:39:46.094 to 2024:194:08:00:56.069
2024-07-23 06:42:30,358 get_aca_images_cached: Getting ACA images from 2024:194:07:39:46.094 to 2024:194:08:00:56.069
2024-07-23 06:42:30,457 get_mon_dataset: Getting MON data from 2024:196:22:32:59.909 to 2024:196:22:37:13.084
2024-07-23 06:42:30,457 get_aca_images_cached: Getting ACA images from 2024:196:22:32:59.909 to 2024:196:22:37:13.084
2024-07-23 06:42:30,543 get_mon_dataset: Getting MON data from 2024:196:23:07:42.709 to 2024:196:23:25:55.359
2024-07-23 06:42:30,543 get_aca_images_cached: Getting ACA images from 2024:196:23:07:42.709 to 2024:196:23:25:55.359
2024-07-23 06:42:30,640 get_mon_dataset: Getting MON data from 2024:196:23:45:41.284 to 2024:197:00:10:12.159
2024-07-23 06:42:30,640 get_aca_images_cached: Getting ACA images from 2024:196:23:45:41.284 to 2024:197:00:10:12.159
2024-07-23 06:42:30,739 get_mon_dataset: Getting MON data from 2024:199:13:03:22.274 to 2024:199:13:41:55.699
2024-07-23 06:42:30,739 get_aca_images_cached: Getting ACA images from 2024:199:13:03:22.274 to 2024:199:13:41:55.699
2024-07-23 06:42:30,848 get_mon_dataset: Getting MON data from 2024:199:14:05:59.924 to 2024:199:14:53:56.074
2024-07-23 06:42:30,848 get_aca_images_cached: Getting ACA images from 2024:199:14:05:59.924 to 2024:199:14:53:56.074
2024-07-23 06:42:31,002 get_mon_dataset: Getting MON data from 2024:202:05:33:00.164 to 2024:202:06:21:26.039
2024-07-23 06:42:31,002 get_aca_images_cached: Getting ACA images from 2024:202:05:33:00.164 to 2024:202:06:21:26.039
2024-07-23 06:42:41,113 _get_tlm: Getting telemetry for 2024:162:13:43:09.061
2024-07-23 06:42:41,185 obss: Getting observations from kadi commands for 2024/Jun-10
2024-07-23 06:42:41,193 _get_tlm: Getting telemetry for 2024:165:05:11:59.317
2024-07-23 06:42:41,267 obss: Getting observations from kadi commands for 2024/Jun-13
2024-07-23 06:42:41,272 _get_tlm: Getting telemetry for 2024:167:20:40:08.097
2024-07-23 06:42:41,344 obss: Getting observations from kadi commands for 2024/Jun-15
2024-07-23 06:42:41,350 _get_tlm: Getting telemetry for 2024:170:12:07:49.613
2024-07-23 06:42:41,421 obss: Getting observations from kadi commands for 2024/Jun-18
2024-07-23 06:42:41,427 _get_tlm: Getting telemetry for 2024:173:03:35:26.811
2024-07-23 06:42:41,497 obss: Getting observations from kadi commands for 2024/Jun-21
2024-07-23 06:42:41,502 _get_tlm: Getting telemetry for 2024:175:19:03:10.976
2024-07-23 06:42:41,572 obss: Getting observations from kadi commands for 2024/Jun-23
2024-07-23 06:42:41,576 _get_tlm: Getting telemetry for 2024:178:10:30:32.525
2024-07-23 06:42:41,644 obss: Getting observations from kadi commands for 2024/Jun-26
2024-07-23 06:42:41,649 _get_tlm: Getting telemetry for 2024:181:01:57:42.556
2024-07-23 06:42:41,723 obss: Getting observations from kadi commands for 2024/Jun-29
2024-07-23 06:42:41,730 _get_tlm: Getting telemetry for 2024:183:17:25:46.279
2024-07-23 06:42:41,802 obss: Getting observations from kadi commands for 2024/Jul-01
2024-07-23 06:42:41,809 _get_tlm: Getting telemetry for 2024:186:08:54:55.680
2024-07-23 06:42:41,882 obss: Getting observations from kadi commands for 2024/Jul-04
2024-07-23 06:42:41,888 _get_tlm: Getting telemetry for 2024:189:00:24:27.187
2024-07-23 06:42:41,959 obss: Getting observations from kadi commands for 2024/Jul-07
2024-07-23 06:42:41,965 _get_tlm: Getting telemetry for 2024:191:15:53:32.737
2024-07-23 06:42:42,037 obss: Getting observations from kadi commands for 2024/Jul-09
2024-07-23 06:42:42,043 _get_tlm: Getting telemetry for 2024:194:07:21:56.140
2024-07-23 06:42:42,116 obss: Getting observations from kadi commands for 2024/Jul-12
2024-07-23 06:42:42,123 _get_tlm: Getting telemetry for 2024:196:22:49:48.288
2024-07-23 06:42:42,196 obss: Getting observations from kadi commands for 2024/Jul-14
2024-07-23 06:42:42,203 _get_tlm: Getting telemetry for 2024:199:14:17:25.860
2024-07-23 06:42:42,274 obss: Getting observations from kadi commands for 2024/Jul-17
2024-07-23 06:42:42,280 _get_tlm: Getting telemetry for 2024:202:05:45:08.820
2024-07-23 06:42:42,351 obss: Getting observations from kadi commands for 2024/Jul-20
2024-07-23 06:42:42,366 get_color_marker_for_perigee: Perigee 2024:162:13:43:09.061 color='C0' marker='o'
2024-07-23 06:42:42,366 get_color_marker_for_perigee: Perigee 2024:165:05:11:59.317 color='C1' marker='o'
2024-07-23 06:42:42,367 get_color_marker_for_perigee: Perigee 2024:167:20:40:08.097 color='C2' marker='o'
2024-07-23 06:42:42,367 get_color_marker_for_perigee: Perigee 2024:170:12:07:49.613 color='C3' marker='o'
2024-07-23 06:42:42,368 get_color_marker_for_perigee: Perigee 2024:173:03:35:26.811 color='C4' marker='o'
2024-07-23 06:42:42,369 get_color_marker_for_perigee: Perigee 2024:175:19:03:10.976 color='C5' marker='o'
2024-07-23 06:42:42,369 get_color_marker_for_perigee: Perigee 2024:178:10:30:32.525 color='C6' marker='o'
2024-07-23 06:42:42,370 get_color_marker_for_perigee: Perigee 2024:181:01:57:42.556 color='C7' marker='o'
2024-07-23 06:42:42,370 get_color_marker_for_perigee: Perigee 2024:183:17:25:46.279 color='C8' marker='o'
2024-07-23 06:42:42,371 get_color_marker_for_perigee: Perigee 2024:186:08:54:55.680 color='C9' marker='o'
2024-07-23 06:42:42,371 get_color_marker_for_perigee: Perigee 2024:189:00:24:27.187 color='C0' marker='^'
2024-07-23 06:42:42,372 get_color_marker_for_perigee: Perigee 2024:191:15:53:32.737 color='C1' marker='^'
2024-07-23 06:42:42,372 get_color_marker_for_perigee: Perigee 2024:194:07:21:56.140 color='C2' marker='^'
2024-07-23 06:42:42,373 get_color_marker_for_perigee: Perigee 2024:196:22:49:48.288 color='C3' marker='^'
2024-07-23 06:42:42,373 get_color_marker_for_perigee: Perigee 2024:199:14:17:25.860 color='C4' marker='^'
2024-07-23 06:42:42,374 get_color_marker_for_perigee: Perigee 2024:202:05:45:08.820 color='C5' marker='^'
2024-07-23 06:42:42,573 clean_aca_images_cache: Cleaning ACA images cache to keep most recent 300 files
```
image

## Side note

The outlier point from 178:1030 + 85 min turns out to be a high-background event. It might be useful to have the high-background event detection code available to use here.

### CODE REVIEW

**Comment by taldcroft** [comment]
@jeanconn - I think this is pretty good to go and we should get the Kalman watch tool going again. I made a mistake in not making a clean bug-fix patch, but probably the best course now is just to get this merged and installed.

**Comment by jeanconn** [comment]
Right, I'm not completely clear on what level of code review to apply to trending codes with outputs just used for by-eye review.  For this, it probably would have been cleanest to make the 2024:152 - 2024:196 plot to show a clean before and after on the the last one that was up.  But given that the code is currently broken and your testing shows that this new code seems to work, I'm good with it.

**Review by jeanconn — APPROVED** [review]
I just reviewed that this testing seems reasonable and the plot looks fine.

**Comment by taldcroft** [comment]
Thanks @jeanconn !

**Pull request merged**
